sudo: required
services:
- docker

script:
- make container

before_deploy:
- echo -n "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin
- echo -n "${GHCR_PASSWORD}" | docker login -u "${GHCR_USERNAME}" --password-stdin ghcr.io

deploy:
  # push taged container to docker hub
  - provider: script
    script: make push
    on:
      branch: master
      tags: true

env:
  global:
  - TARGET=linux/arm64,linux/amd64 # multiple architectures build in one step
  - BUILD_FLAGS=--no-cache # no --load flag, with multiple architectures
  - secure: hs8m9KkJ+sBwQr4FF/ZGFDpK25n4K3q6R/KU0q++m27G0D2XtO+JeTQnRi8cV/8JGcYClBUIqkIXoKxpohuZ+LrTUGtPL/KUjsMshV59PTqvCrlkCmUfMrM0DowwVW1O7g2T+gPsr0rj++FUxTtk0s12sHZdxTDFrNTtdFD6Et6BXO6UIlDy2PhhLXNf7kxa7OpWPOWXosU6bBuj4NjaGXpYSWIJPnxMbmfGcmOpudPeRJGJsqDmHy3YKZ8IDWKOsDNOKmltOAzG3qhQP2DhHfjC4Tpmou3AOD2SdI5ekwPvQpa4cWo7LOw6l6PYtz7MhfchnQR5+KXvTu+JvGt3LDJeuE8PmFzefOxO2fUoEjNGFa3hRxGzJ4UyzxyXrqwPH4XBm4x1sqVFqMEwkY3AsuACGk4+1CSVkXORtE4GrhLBi52cJ7EI0Qq02+WjSKGppRg1OjIX0ZRG/mGOnt/qqHLSfxmRJGPIgtIALtsTbbHZwQN67se08p1+4JHgQ6G4tEV27Kmsu6tz2oAJrOuPrhCNltRFPhYw3A4U4jIO9ziMJHSMLtsHu48cOTtw2tVNW4mss6wadqpL4akX7uEiFoBrf0YFQ1cpImtpjRcAV8izBFiLYYLnQrnXUAPDFIEPEgyax8JATWVCS1qnfbdB3++6CUEMceTpBpY7dQVimKY=
  - secure: eGI6porT74KMcar09zF6UQNpeQ28/2zrVRuxRV0jjQ2+gAlJrbZjROZg8vZ9jKimWoks8MAGdo1y7s99pGVJ8yOT+yHX2C3ZOStFdLWTXVxeEZrsg0xd11qKB7/RmlLt0/Nsy1lvA/UM7h4ydAhIXO7jxSxltHyyUaW8SrUGpku6prpUJGQVAuJgK6MdBSw+H5kjk9FLyQxTs54h+GQBoFtTucmf+DLdSkahH6+La7zHYitNr/Q++ghIbzvwuHzJ24ZCKJfY3mlwIymcoGtflULwuClJnkp0I07rht2mgrx9/SXzOfstBcT85OSsSOAUzv0RjTx34WxaanfD/cgk1jr51+jAXbHq7mpcFpc7MxX+uS3r+LpSksJe6MTcvJB03zUkHm0Y8qsg1GnmDeyY61CBTKi0QIR5+RrwBGQKBzuUFvq90fhBFTBOGEmxRMx7IQNT+o3OcugaAirfYSIfd1aFcBUZml/KxVTTTjGooyHaqYlDH1TuZ489/4H3H2VL/Waf+QcB5e+c7VYvl7o/8ZpHxmRon0dlUxeS2yqowex1lB9ZvXaXUcUf9DZXsMB9Iym1HR1enwyDxXlgs9H72eksLX08mY703l2sujQrzZnQg3p1w11lK7aDaYqX/HguSakkiwziwoCTzfphVxrjQyYZbgPkPMWnUazf5Im1jmM=
  - secure: STKKi64NfO1X+o6CVUNZaZaTpcxAqQ99PPMA0zSoNwhg+e6xu8rF3maB3GM0EjTYZ4w2hccVp8fyHetsrVJX7sTPoo85dfNzQi8/o0MpLugyKLYytGW+BFJJWcG8SJh+Qp28rLRKD+T38eLuQugwoTPWmVq6H5khR4PCasi+FF4yz1GkdiD2AyOYXAIfH4NvbifuA3U5yvuMtHASRIUGSJJvIMhyALcUC6XxbNXB+Ugvq1RvlkVSEh2sxP24A+A4CERzyQbVEMzC235qucUhwcUne+4EuGPQi+g+P3e5lBmZGf+uYhhncrPJWGZp7/NgI1ClyU5n2VZNCune+IS0E7JsK6umabN2K4385EJqCOwOka1N8q4lvfCkynIIylqSGkRBgsgpDq7e/tYfxr4tl7mCxUyTRGvGKL/0i68rdnllCQ+ndFNS6H0/ltCdHxnac5+tbN10tspdwCAfVu+g4Vgj3Yl4Uk3M5BbS03OIbVB3/dqMRmjBPANEJ267v7JXLcHSCAtONDGwWcGae0ZEUtiVMSPHTqgELPjpHsK0tTmGMFgT9hh27iHyGvBErB+ec7Fz7ayTQUbDK8ZoKwY+isAubUR+pAyB/5dcqwhYYNb041/ScRtfwdHjrheL2V0vFI7SPCavbeCMaY0ZGOySy5WhcvT6V/LayGjpedEj8SA=
  - secure: ZGtb+VTJengJeZHTFgybPFtaoaWhC4BS6Ees8GEbksFwSKxdA3YbF1WeeNI3gQHo5XJEw8h7Dtpc8vzMciLFjfC0ZQz2/sxFC9c3YN4Hb4kGhGZ5BrDxDMTMFBPm2ctki2QzW2Dt3c1GgDBFtIe33Cejxds79bZdMm89OxBzG+b0iFBZCFwdwx7sbir21MMZOB2N+icyHVZ99PXF5tnB5P5wXByF9i0muScSvrKiXs0TeFP3E4mrQZH0gujqOtFvUXt3XmqsIAU4HNbEzFQb27oEdNliCY81ldTdlrvT3RS/vNBkNrUVyvvlrNwieKXE3+XEuIuo3+ajx0vzHaK7ryK/b8dnnKaPnXDY9yT4iXLTrD1UvpAuSZ3UbLUkIx49sM7TRzw6dL8e6rqRhUvzY7HehKCV/vx00wxy7czTdw8b7oKPQaJJHQcqMjIDX7Uxo1d3UDu1EqoDGtkqMBswdh/adF+D2kTzFEHqDCNHO14+w5htZ2ZO6PhfPecdI9+2T8A6+gZcu0r0Ds4C8VrrfrMHaIdFigQjruUuTq1bOLHfe3rvOHv99z+UiRMvkpxKGtbuuvPp+zZeBprjT5dSJBOC+4ICOo1lfnG7dB1SAcyL4WkRvprDpAtoxP28Xn6lLoyXNEyfB6BSjNjeGw29b4csVjYvKEoH4BCId7TLcpg=
  jobs:
  - DOCKER_FILE=Dockerfile DOCKER_IMAGE=
  - DOCKER_FILE=DockerfileRootless DOCKER_IMAGE=rootless.